### ISSUE TITLE
ERC20 Support

### ISSUE THREAD

**Issue by D4nte** [coblox/bobtimus#21]
Update bobtimus to support ERC20 and deploy action.

What do discuss: 
- How to configure the rate in the config file.

DoD: 
- Bobtimus supports swapping X-ERC20
- TestnetMarketMaker needs updating

Tasks:
- [x] Make Asset enum a class to allow flexibility for erc20 #91 
- [x] Update Ethereum wallet to support ERC20 (balance) #92 
- [x] Predefine supported tokens in config file #96 
  - config file would contain symbol, address and decimals
  - symbols are then used for static rate and logging
  - at bobtimus start, configured symbol and decimals can be doubled check against actual contract to avoid misleading/confusion/error
- [x] Update static rate to support erc20 #97
- [x] Update `actionSelector` to support erc20 #98
- ~Update `actionExecutor` to support erc20~ <-- No change needed
- [x] Update testnet Market maker #100
- [ ] Update REST API to return enough details for client to generate comit link

**Comment by D4nte** [comment]
Proposal:
- Update Ethereum wallet to support ERC20
- Predefine supported tokens in config file
- Update static rate to support erc20
- Update execution classes (`actionExecutor`, `actionSelector`, `ledgerExecutor`) to support erc20
- Update testnet Market maker

Uncertainty: not sure how the new erc20 asset will look like in comparison to bitcoin/ether `Asset`s
